// <auto-generated />
using System;
using LogAnalyzerForWindows.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LogAnalyzerForWindows.Migrations
{
    [DbContext(typeof(LogAnalyzerDbContext))]
    [Migration("20260203190033_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("LogAnalyzerForWindows.Models.LogEntryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Level")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_LogEntries_CreatedAt");

                    b.HasIndex("EventId")
                        .HasDatabaseName("IX_LogEntries_EventId");

                    b.HasIndex("Level")
                        .HasDatabaseName("IX_LogEntries_Level");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("IX_LogEntries_SessionId");

                    b.HasIndex("Source")
                        .HasDatabaseName("IX_LogEntries_Source");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("IX_LogEntries_Timestamp");

                    b.HasIndex("Level", "Timestamp")
                        .HasDatabaseName("IX_LogEntries_Level_Timestamp");

                    b.HasIndex("SessionId", "Level")
                        .HasDatabaseName("IX_LogEntries_SessionId_Level");

                    b.HasIndex("SessionId", "Source")
                        .HasDatabaseName("IX_LogEntries_SessionId_Source");

                    b.HasIndex("SessionId", "Timestamp")
                        .HasDatabaseName("IX_LogEntries_SessionId_Timestamp");

                    b.ToTable("LogEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
